### ISSUE TITLE
Last, First, Suffix pattern is not parsed properly

### ISSUE THREAD

**Issue by adrienne** [theiconic/name-parser#18]
One common (if slightly archaic) way of listing names is as follows:

**Lastname, Firstname (optional middle initial or name), Suffix**

for example:

**Tiptree, James, Jr.** 
which the parser parses as:
```
[
lastname => string (13) "Tiptree James"
suffix => string (2) "Jr"
]
```

and

**Miller, Walter M., Jr.**
which the parser parses as:
```
[
firstname => string (6) "Walter"
lastname => string (9) "Miller M."
suffix => string (2) "Jr"
]
```

Interestingly, if you remove the second comma, the names behave differently.

**Tiptree, James Jr.** still fails (it drops the suffix):
```
[
firstname => string (5) "James"
lastname => string (7) "Tiptree"
]
```

**Miller, Walter M. Jr.** correctly parses into firstname/initial/lastname/suffix, as shown:
```
[
firstname => string (6) "Walter"
lastname => string (6) "Miller"
initials => string (2) "M."
suffix => string (2) "Jr"
]
```

So, definitely a few problems to fix here!

**Comment by adrienne** [comment]
(In general, this parser is the best one I've found; among other things, it's the *only* one that I've found that correctly handles mononyms. So i'd really love it if this could get fixed!)

**Comment by adrienne** [comment]
@wyrfel possibly I should tag you on this? You seem to be a maintainer!

**Comment by wyrfel** [comment]
Hey @adrienne. Thanks for reporting the issue (and the nice feedback, btw). I'll look into it as soon as i can.

**Comment by wyrfel** [comment]
@adrienne I was unable to reproduce the issue with with the `lastname, firstname, suffix` patterns.
I have added test cases for the scenarios you reported [here](https://github.com/theiconic/name-parser/pull/19/files#diff-a377c15a7e1f14404909ee29854b60abR458) and the tests are not failing.

I have also made a slight modification in this PR to allow the parsing of e.g. 'Jr.' as suffix instead of middle name in 'Tiptree, James Jr.'.

Could you please make sure you are using the latest version and could you let me now if you have made any configuration changes, language changes or any other customisations?
