### ISSUE TITLE
Overriding or appending to arrays (such as salutations)

### ISSUE THREAD

**Issue by ryancwalsh** [theiconic/name-parser#23]
This library is amazing! Thanks so much for providing it!

It's the best one I've found.

I was wondering if there is an easy way to initialize the library with configurable settings, such as if I want to change the salutations that I see in https://github.com/theiconic/name-parser/blob/master/src/Language/English.php

E.g. I may want to add  "Prof." as a salutation.

Or maybe there are occasions where I'd want to customize the other constant arrays there.

Other than forking your repo and editing the code, I haven't figured it out yet. 

Thanks again!

**Comment by wyrfel** [comment]
@ryancwalsh Thanks for the compliments.
Yes, you can create your own language class, say `RyansEnglish` that either extends `English` or just implements `LanguageInterface` on its own. You can then instantiate the parser with that class instead of English, like so:
```
$languages = [
    new RyansEnglish(),
];
$parser = new Parser($languages);
```
If you want to extend more so than modify, you can also develop your class as an add-on (rather than a replacement) to the English defaults and pass both like so:
```
$languages = [
    new English(),
    new RyansEnglish(),
];
$parser = new Parser($languages);
```
Pease let me know if this is what you were after.

(Please note that I have dropped any namespaces in the code examples for brevity.)

**Comment by ryancwalsh** [comment]
I'm excited to try this! Thank you!

**Comment by ryancwalsh** [comment]
Reopening.

Are you sure this works? I've tried a bunch without luck and think there might be an issue here:

https://github.com/theiconic/name-parser/blob/71fc4f4a08af85d738e1942acf0a30b4dc0d7105/src/Parser.php#L104

(and other lines like it) calls `$parser = new Parser();` without the languages param.

**Comment by wyrfel** [comment]
Hey @ryancwalsh . Nice spotting, there is indeed a bit of an issue there with the use of the parsers. But it should work, still, because the actual values for salutations etc. are acquired from the languages set on the original parser and then injected right into the mappers when configuring those sub-parsers (just a few lines below the one you quoted).

Can you elaborate or share the full code snippet for the case that doesn't work for you, please?

**Comment by ryancwalsh** [comment]
@wyrfel Ahhh, you are right. I was mistaken. I apologize.

Everything works perfectly, and I really appreciate this library! Thanks!

Here is what I used:

```
class NameParserEnglishAddon extends \TheIconic\NameParser\Language\English {

    const SALUTATIONS = [
        'prof' => 'Prof.'
    ];

    public function getSalutations(): array {//My problem was that I'd neglected to create this function.
        return array_merge(self::SALUTATIONS, parent::SALUTATIONS);
    }

}
```
