### ISSUE TITLE
Lastname is one of the recognised prefixes

### ISSUE THREAD

**Issue by garywarner** [theiconic/name-parser#25]
Thanks for your work on this library - much appreciated.

We had a failure today for "yumeng du" as a name.
Looking at the parts array, the 'du' is not ascribed to a part.
I'm guessing that this is because it's one of the recognised prefixes?

**Comment by wyrfel** [comment]
Hey @garywarner. Glad to hear you found good use for the library. I just added a test case for 'Yumeng Du' and it does get parsed into firstname: Yumeng, lastname: Du. Can you please verify this again?
'Du' is in fact registered as a lastname prefix, but if there are no additional parts, lastname prefixes will still be treated as the lastname because [we check first](https://github.com/theiconic/name-parser/blob/c8501749a499bdb548002d40bca76ac7d7dc215c/src/Mapper/LastnameMapper.php#L59) if another lastname part has already been identified before we interpret something as prefix.
Can you please check if 'Yumeng Du' was in fact the full input string or if there was maybe some additional characters in that string?

**Comment by wyrfel** [comment]
@garywarner I'm closing this on the basis that the test succeeds. Please re-open if you still have the issue.

**Comment by garywarner** [comment]
@wyrfel Happy you've closed this - all I needed to do was bump my version. Thank you so much for running the test and sending me in the right direction. 👏
